version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed Successfully on `date`
artifacts:
  files:
    - target/user-service.jar
  discard-paths: yes