apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: develop
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-service-container
          image: 'javaexpress/springboot-docker'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
