apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: develop
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-service-container
          image: akhilgolla/springboot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: develop
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8085
  type: NodePort
