apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: develop
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8085
  type: NodePort
