apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: user-dev
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8085
  type: NodePort